# Generated by Django 5.1.7 on 2025-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_produit_completed_produit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
